name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]  # adjust as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt  # if available

      - name: Run unit tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Run quality checks with flake8 and pylint
        run: |
          flake8 .
          pylint your_package_name  # replace with your actual package or module name

      - name: Upload coverage to Codecov
        run: |
          codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}